# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

plugin 'cocoapods-art', :sources => [
  'beanstream-public'
]

target 'CheckoutPodTester' do
  pod 'Checkout', '~> 0.4.0'
end

